Repository KTH-DD2480-Group-2/Algorithms, pull requests merged in 2021-02, with the labels that each got.

#2 #1 docs: Add Jacoco to to the project and include lizard's results in README
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation, ready for review

#12 #7 feat: Create a statistic program for coverage
  README.md
  build.gradle
  diy-branch-coverage-control.txt
  src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java
  src/main/java/com/williamfiset/algorithms/utils/BranchCoverageAnalyser.java
  src/main/java/com/williamfiset/algorithms/utils/CoverageStatistics.java
  src/test/java/com/williamfiset/algorithms/datastructures/utils/TreePrinterTest.java
  src/test/java/com/williamfiset/algorithms/utils/CoverageStatisticsTest.java
Labels: enhancement

#13 #3 feat: Improve getTreeDisplay in TreePrinter.java
  build.gradle
  src/main/java/com/williamfiset/algorithms/datastructures/utils/TreePrinter.java
  src/test/java/com/williamfiset/algorithms/datastructures/utils/TreePrinterTest.java
Labels: ready for review

#19 #4 feat: Improve knn() in QuadTree
  build.gradle
  src/main/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTree.java
  src/test/java/com/williamfiset/algorithms/datastructures/quadtree/QuadTreeTest.java
  src/test/java/com/williamfiset/algorithms/datastructures/utils/TreePrinterTest.java
Labels: ready for review

#14 #8 feat: Improve lineSegmentLineSegmentIntersection() in LineSegmentIntersection
  src/main/java/com/williamfiset/algorithms/geometry/LineSegmentLineSegmentIntersection.java
  src/test/java/com/williamfiset/algorithms/geometry/LineSegmentLineSegmentIntersectionTest.java
Labels: ready for review

#21 #10 feat: Improve encodeTree() in TreeIsomorphismWithBfs
  src/main/java/com/williamfiset/algorithms/graphtheory/treealgorithms/TreeIsomorphismWithBfs.java
  src/test/java/com/williamfiset/algorithms/graphtheory/treealgorithms/TreeIsomorphismWithBfsTest.java
Labels: ready for review

#23 #22 docs: add statement of contributions
  README.md
Labels: documentation
